#!/usr/bin/bash
status="$( playerctl metadata -f '{{artist}}: {{title}}' | sed 's/ - Topic//' )"

play_pause="$( playerctl status )"

if [[ "$play_pause" ==  "Playing" ]]; then
    icon=""
else
    icon=""
fi

echo "$icon $status"
