[character]
success_symbol = "[❯](bold green) "
error_symbol = "[❯](bold red) "
vicmd_symbol = " "

[kubernetes]
format = "$symbol[$context](purple) "
disabled = false
symbol = "ﴱ "
[kubernetes.context_aliases]
".*tkg.*mgmt.*admin.*" = "tkg-mgmt"
".*tkg.*mgmt.*" = "tkg-mgmt"

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "
format = 'via [$symbol]($style)'

[dart]
symbol = " "
format = 'via [$symbol]($style)'

[directory]
read_only = " "
style = "italic cyan"
format = "[$path]($style) "

[docker_context]
symbol = " "
format = 'via [$symbol]($style)'

[elixir]
symbol = " "
format = 'via [$symbol]($style)'

[elm]
symbol = " "
format = 'via [$symbol]($style)'

[git_branch]
symbol = " "
style = "purple"

[golang]
symbol = " "
format = 'via [$symbol]($style)'

[hg_branch]
symbol = " "

[java]
symbol = " "
format = 'via [$symbol]($style)'

[julia]
symbol = " "
format = 'via [$symbol]($style)'

[memory_usage]
symbol = " "

[nim]
symbol = " "
format = 'via [$symbol]($style)'

[nix_shell]
symbol = " "
format = 'via [$symbol]($style)'

[nodejs]
symbol = " "
format = 'via [$symbol]($style)'

[package]
symbol = " "
disabled = true

[perl]
symbol = " "
format = 'via [$symbol]($style)'

[php]
symbol = " "
format = 'via [$symbol]($style)'

[python]
symbol = " "
format = 'via [$symbol]($style)'

[ruby]
symbol = " "
format = 'via [$symbol]($style)'

[rust]
symbol = " "
format = 'via [$symbol]($style)'

[swift]
symbol = "ﯣ "
format = 'via [$symbol]($style)'
