#!/bin/sh


pick-emoji() {

  MENU=$(fzf << EOF
  dh
  area
  health
  finance
  career
  character
  home
  gb
  goals
  milestones
  projects
  achievements
  quests
  checkpoints
  EOF)

  case "$MENU" in
      dh) echo "💯" | pbcopy;;
      area) echo " " | pbcopy;;
      health) echo " " | copy;;
      finance) echo " " | pbcopy;;
      career) echo " " | pbcopy;;
      character) echo " " | pbcopy;;
      home) echo " " | pbcopy;;
      gb) echo "" | pbcopy;;
      goals) echo "🎯"| pbcopy;;
      milestones) echo "🏆" | pbcopy;;
      achievements) echo " " | pbcopy;;
      projects) echo " " | pbcopy;;
      quests) echo "理" | pbcopy;;
      checkpoints) echo "輻" | pbcopy;;
  esac
}
