{{- /* chezmoi:modify-template */ -}}
{{- /* chezmoi:template:missing-key=zero */ -}}
{{- $config := fromYaml .chezmoi.stdin }}
{{- $theme := (env "THEME" | lower) | default "catppuccin-mocha" }}
k9s:
  liveViewAutoRefresh: true
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: true
  headless: false
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: true
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
{{- if $config.k9s }}
  {{- if $config.k9s.currentContext }}
  currentContext: {{ $config.k9s.currentContext }}
  {{- end }}
  {{- if $config.k9s.currentCluster }}
  currentCluster: {{ $config.k9s.currentCluster }}
  {{- end }}
  {{- if $config.k9s.clusters }}
  clusters:
    {{- range $name, $cluster := $config.k9s.clusters }}
    {{ $name }}:
      {{- $cluster | setValueAtPath "featureGates.nodeShell" true | setValueAtPath "skin" $theme | toYaml | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: {{env "TMPDIR" | default "/tmp" }}k9s-screens-{{ env "USER" | default "user" }}
