#!/bin/sh

dotfile-call() {
  # if passed no args then fuzzy search a state to run
  if [ -z "$1" ]; then
    ls /etc/srv/dotfiles | fzf | xargs basename -s ".sls" | xargs sudo salt-call state.apply
  else
    sudo salt-call state.apply "$@"
  fi
}
