["Library/Preferences/glow/themes/frappe.json"]
type = "file"
url = "https://github.com/catppuccin/glamour/raw/main/themes/catppuccin-frappe.json"
refreshPeriod = "168h"
["Library/Preferences/glow/themes/latte.json"]
type = "file"
url = "https://github.com/catppuccin/glamour/raw/main/themes/catppuccin-latte.json"
refreshPeriod = "168h"
["Library/Preferences/glow/themes/macchiato.json"]
type = "file"
url = "https://github.com/catppuccin/glamour/raw/main/themes/catppuccin-macchiato.json"
refreshPeriod = "168h"
["Library/Preferences/glow/themes/mocha.json"]
type = "file"
url = "https://github.com/catppuccin/glamour/raw/main/themes/catppuccin-mocha.json"
refreshPeriod = "168h"
