["Library/Fonts/sketchybar-app-font.ttf"]
    type = "file"
    url = "https://github.com/kvndrsslr/sketchybar-app-font/releases/download/latest/sketchybar-app-font.ttf"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
