format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $hg_branch\
  $package\
  $golang\
  $nodejs\
  $php\
  $python\
  $ruby\
  $rust\
  $terraform\
  $kubernetes\
  $memory_usage\
  $aws\
  $env_var\
  $cmd_duration\
  $line_break\
  $jobs\
  $time\
  $character\
"""


[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = " "

[kubernetes]
format = "within "
disabled = false
symbol = " "

[aws]
symbol = " "
disabled = true

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "

[docker]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "bold red"

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

