#! /bin/sh

sxhkd &
dunst -conf ~/.config/dunst/dunstrc &
hsetroot -solid "#1e1c31" &
setup-second-monitor &
~/.config/polybar/launch.sh --titan &
xsetroot -cursor_name left_ptr &

if has-two-monitors ; then
    bspc monitor 'DisplayPort-0' -d 1 2 3 4
    bspc monitor 'DisplayPort-1' -d 5 6
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9
fi

bspc config border_width        1
bspc config normal_border_color  "#585273"
bspc config focused_border_color "#63F2F1"
bspc config window_gap          12
bspc config top_padding         42

bspc config automatic_scheme alternate
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer      true

bspc rule -a kitty desktop='1'
bspc rule -a firefox desktop='2'
bspc rile -a zoom desktop='2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty-scratch sticky=true hidden=true

firefox &
kitty &
THEME=gruvbox-light kitty --listen-on=unix:/tmp/kitty-scratch --class kitty-scratch --config ~/.config/kitty/kitty-scratch.conf --hold --directory=$HOME &

bspc desktop '3' -f
spotify &
sleep 2

kitty @ --to=unix:/tmp/kitty-scratch set-colors --all $HOME/.config/kitty/gruvbox-light.conf
